spring:
  datasource:
    url: jdbc:mysql://39.106.142.14:3306/panis_boot?socketTimeout=60000&connectTimeout=30000&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 9988174
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      database: 1
      host: 39.106.142.14
      connect-timeout: 10000ms
      lettuce:
        pool:
          enabled: true
      password: 9988174
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.baomidou.mybatisplus: debug
